[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional cache configuration
[[plugins]]
  package = "@netlify/cache-utils"
  inputs = { cache = "true" }
